export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_AUTH_POPUP = 'SET_AUTH_POPUP';
export const SET_SIGNUP_AUTH_POPUP = 'SET_SIGNUP_AUTH_POPUP';
export const SET_FORGOT_AUTH_POPUP = 'SET_FORGOT_AUTH_POPUP';

export const LOG_OUT_USER = 'LOG_OUT_USER';
/* SETTINGS */

/* AUTH */
export const GET_USER_DETAILS = 'GET_USER_DETAILS';

export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_ERROR = 'GET_USER_DETAILS_ERROR';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const SIGNUP_USER = 'SIGNUP_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR = 'SIGNUP_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';

export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_ERROR = 'UPDATE_USER_DETAILS_ERROR';

export const OTP_VERIFY = 'OTP_VERIFY';

export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_ERROR = 'OTP_VERIFY_ERROR';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

/* TODOAPP */
export const TODO_GET_LIST = 'TODO_GET_LIST';
export const TODO_GET_LIST_SUCCESS = 'TODO_GET_LIST_SUCCESS';
export const TODO_GET_LIST_ERROR = 'TODO_GET_LIST_ERROR';
export const TODO_GET_LIST_WITH_FILTER = 'TODO_GET_LIST_WITH_FILTER';
export const TODO_GET_LIST_WITH_ORDER = 'TODO_GET_LIST_WITH_ORDER';
export const TODO_GET_LIST_SEARCH = 'TODO_GET_LIST_SEARCH';
export const TODO_ADD_ITEM = 'TODO_ADD_ITEM';
export const TODO_ADD_ITEM_SUCCESS = 'TODO_ADD_ITEM_SUCCESS';
export const TODO_ADD_ITEM_ERROR = 'TODO_ADD_ITEM_ERROR';
export const TODO_SELECTED_ITEMS_CHANGE = 'TODO_SELECTED_ITEMS_CHANGE';

/* CHAT APP */
export const CHAT_GET_CONTACTS = 'CHAT_GET_CONTACTS';
export const CHAT_GET_CONTACTS_SUCCESS = 'CHAT_GET_CONTACTS_SUCCESS';
export const CHAT_GET_CONTACTS_ERROR = 'CHAT_GET_CONTACTS_ERROR';
export const CHAT_GET_CONVERSATIONS = 'CHAT_GET_CONVERSATIONS';
export const CHAT_GET_CONVERSATIONS_SUCCESS = 'CHAT_GET_CONVERSATIONS_SUCCESS';
export const CHAT_GET_CONVERSATIONS_ERROR = 'CHAT_GET_CONVERSATIONS_ERROR';
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  'CHAT_ADD_MESSAGE_TO_CONVERSATION';
export const CHAT_CREATE_CONVERSATION = 'CHAT_CREATE_CONVERSATION';
export const CHAT_SEARCH_CONTACT = 'CHAT_SEARCH_CONTACT';
export const CHAT_CHANGE_CONVERSATION = 'CHAT_CHANGE_CONVERSATION';

/* SURVEY LIST APP */
export const SURVEY_LIST_GET_LIST = 'SURVEY_LIST_GET_LIST';
export const SURVEY_LIST_GET_LIST_SUCCESS = 'SURVEY_LIST_GET_LIST_SUCCESS';
export const SURVEY_LIST_GET_LIST_ERROR = 'SURVEY_LIST_GET_LIST_ERROR';
export const SURVEY_LIST_GET_LIST_WITH_FILTER =
  'SURVEY_LIST_GET_LIST_WITH_FILTER';
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  'SURVEY_LIST_GET_LIST_WITH_ORDER';
export const SURVEY_LIST_GET_LIST_SEARCH = 'SURVEY_LIST_GET_LIST_SEARCH';
export const SURVEY_LIST_ADD_ITEM = 'SURVEY_LIST_ADD_ITEM';
export const SURVEY_LIST_ADD_ITEM_SUCCESS = 'SURVEY_LIST_ADD_ITEM_SUCCESS';
export const SURVEY_LIST_ADD_ITEM_ERROR = 'SURVEY_LIST_ADD_ITEM_ERROR';
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  'SURVEY_LIST_SELECTED_ITEMS_CHANGE';

/* SURVEY DETAIL APP */
export const SURVEY_GET_DETAILS = 'SURVEY_GET_DETAILS';
export const SURVEY_GET_DETAILS_SUCCESS = 'SURVEY_GET_DETAILS_SUCCESS';
export const SURVEY_GET_DETAILS_ERROR = 'SURVEY_GET_DETAILS_ERROR';
export const SURVEY_DELETE_QUESTION = 'SURVEY_DELETE_QUESTION';
export const SURVEY_SAVE = 'SURVEY_SAVE';

// BRAND AND CATEGORY
export const ADD_BRAND_AND_CATEGORY = 'ADD_BRAND_AND_CATEGORY';
export const ADD_BRAND_AND_CATEGORY_SUCCESS = 'ADD_BRAND_AND_CATEGORY_SUCCESS';
export const ADD_BRAND_AND_CATEGORY_ERROR = 'ADD_BRAND_AND_CATEGORY_ERROR';
export const GET_BRAND_AND_CATEGORY = 'GET_BRAND_AND_CATEGORY';
export const GET_BRAND_AND_CATEGORY_SUCCESS = 'GET_BRAND_AND_CATEGORY_SUCCESS';
export const GET_BRAND_AND_CATEGORY_ERROR = 'GET_BRAND_AND_CATEGORY_ERROR';
export const UPDATE_BRAND_AND_CATEGORY = 'UPDATE_BRAND_AND_CATEGORY';
export const UPDATE_BRAND_AND_CATEGORY_SUCCESS =
  'UPDATE_BRAND_AND_CATEGORY_SUCCESS';
export const UPDATE_BRAND_AND_CATEGORY_ERROR =
  'UPDATE_BRAND_AND_CATEGORY_ERROR';

export const DELETE_BRAND_AND_CATEGORY = 'DELETE_BRAND_AND_CATEGORY';
export const DELETE_BRAND_AND_CATEGORY_SUCCESS =
  'DELETE_BRAND_AND_CATEGORY_SUCCESS';
export const DELETE_BRAND_AND_CATEGORY_ERROR =
  'DELETE_BRAND_AND_CATEGORY_ERROR';

// Product

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const GET_HOMESCREEN_DATA = 'GET_HOMESCREEN_DATA';
export const GET_HOMESCREEN_DATA_SUCCESS = 'GET_HOMESCREEN_DATA_SUCCESS';
export const GET_HOMESCREEN_DATA_ERROR = 'GET_HOMESCREEN_DATA_ERROR';

// Offer

export const ADD_OFFER = 'ADD_OFFER';
export const ADD_OFFER_SUCCESS = 'ADD_OFFER_SUCCESS';
export const ADD_OFFER_ERROR = 'ADD_OFFER_ERROR';
export const GET_SINGLE_OFFER = 'GET_SINGLE_OFFER';
export const GET_SINGLE_OFFER_SUCCESS = 'GET_SINGLE_OFFER_SUCCESS';
export const GET_SINGLE_OFFER_ERROR = 'GET_SINGLE_OFFER_ERROR';
export const UPDATE_OFFER = 'UPDATE_OFFER';
export const UPDATE_OFFER_SUCCESS = 'UPDATE_OFFER_SUCCESS';
export const UPDATE_OFFER_ERROR = 'UPDATE_OFFER_ERROR';
export const DELETE_OFFER = 'DELETE_OFFER';
export const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS';
export const DELETE_OFFER_ERROR = 'DELETE_OFFER_ERROR';
export const GET_OFFERS = 'GET_OFFERS';
export const GET_OFFERS_SUCCESS = 'GET_OFFERS_SUCCESS';
export const GET_OFFERS_ERROR = 'GET_OFFERS_ERROR';

// wishlist
export const GET_WISHLIST_DETAILS = 'GET_WISHLIST_DETAILS';
export const GET_WISHLIST_DETAILS_SUCCESS = 'GET_WISHLIST_DETAILS_SUCCESS';
export const GET_WISHLIST_DETAILS_ERROR = 'GET_WISHLIST_DETAILS_ERROR';
export const ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST';
export const ADD_PRODUCT_TO_WISHLIST_SUCCESS =
  'ADD_PRODUCT_TO_WISHLIST_SUCCESS';
export const ADD_PRODUCT_TO_WISHLIST_ERROR = 'ADD_PRODUCT_TO_WISHLIST_ERROR';
export const DELETE_PRODUCT_FROM_WISHLIST = 'DELETE_PRODUCT_FROM_WISHLIST';
export const DELETE_PRODUCT_FROM_WISHLIST_SUCCESS =
  'DELETE_PRODUCT_FROM_WISHLIST_SUCCESS';
export const DELETE_PRODUCT_FROM_WISHLIST_ERROR =
  'DELETE_PRODUCT_FROM_WISHLIST_ERROR';

// cart
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_ERROR = 'ADD_PRODUCT_TO_CART_ERROR';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const DELETE_PRODUCT_FROM_CART_SUCCESS =
  'DELETE_PRODUCT_FROM_CART_SUCCESS';
export const DELETE_PRODUCT_FROM_CART_ERROR = 'DELETE_PRODUCT_FROM_CART_ERROR';

// address
export const DELIVER_TO_THIS_ADDRESS = 'DELIVER_TO_THIS_ADDRESS';
export const GET_USER_ADDRESS = 'GET_USER_ADDRESS';
export const GET_USER_ADDRESS_SUCCESS = 'GET_USER_ADDRESS_SUCCESS';
export const GET_USER_ADDRESS_ERROR = 'GET_USER_ADDRESS_ERROR';
export const CREATE_USER_ADDRESS = 'CREATE_USER_ADDRESS';
export const CREATE_USER_ADDRESS_SUCCESS = 'CREATE_USER_ADDRESS_SUCCESS';
export const CREATE_USER_ADDRESS_ERROR = 'CREATE_USER_ADDRESS_ERROR';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const UPDATE_USER_ADDRESS_SUCCESS = 'UPDATE_USER_ADDRESS_SUCCESS';
export const UPDATE_USER_ADDRESS_ERROR = 'UPDATE_USER_ADDRESS_ERROR';
export const DELETE_USER_ADDRESS = 'DELETE_USER_ADDRESS';
export const DELETE_USER_ADDRESS_SUCCESS = 'DELETE_USER_ADDRESS_SUCCESS';
export const DELETE_USER_ADDRESS_ERROR = 'DELETE_USER_ADDRESS_ERROR';
export const GET_ADDRESS_BY_ID = 'GET_ADDRESS_BY_ID';
export const GET_ADDRESS_BY_ID_SUCCESS = 'GET_ADDRESS_BY_ID_SUCCESS';
export const GET_ADDRESS_BY_ID_ERROR = 'GET_ADDRESS_BY_ID_ERROR';

// review
export const LIKE_DISLIKE_PRODUCT_REVIEW = 'LIKE_DISLIKE_PRODUCT_REVIEW';
export const ADD_EDIT_USER_REVIEW = 'ADD_EDIT_USER_REVIEW';

// order
export const GET_USER_ORDERS = 'GET_USER_ORDERS';
export const GET_USER_ORDERS_SUCCESS = 'GET_USER_ORDERS_SUCCESS';
export const GET_USER_ORDERS_ERROR = 'GET_USER_ORDERS_ERROR';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_ERROR = 'GET_ORDER_BY_ID_ERROR';

// blogs
export const GET_BLOGS = 'GET_BLOGS';
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS';
export const GET_BLOGS_ERROR = 'GET_BLOGS_ERROR';

export const GET_BLOG_BY_ID = 'GET_BLOG_BY_ID';
export const GET_BLOG_BY_ID_SUCCESS = 'GET_BLOG_BY_ID_SUCCESS';
export const GET_BLOG_BY_ID_ERROR = 'GET_BLOG_BY_ID_ERROR';
